export const appointmentListStyles = {
  container: "bg-white rounded-xl p-6 shadow-md",
  listHeader: "flex justify-between items-center mb-6",
  listHeaderTitle: "m-0 text-gray-800 text-xl",
  filterContainer: "[&_select]:py-2 [&_select]:px-4 [&_select]:border-2 [&_select]:border-gray-200 [&_select]:rounded-md [&_select]:text-[0.9rem] [&_select]:cursor-pointer [&_select:focus]:outline-none [&_select:focus]:border-primary",
  errorMessage: "bg-red-100 text-red-600 py-3 px-4 rounded-md mb-4 text-[0.9rem]",
  emptyState: "text-center py-12 px-4 text-gray-500",
  appointmentsGrid: "grid grid-cols-[repeat(auto-fill,minmax(320px,1fr))] gap-4",
  appointmentCard: "border-2 border-gray-200 rounded-xl overflow-hidden transition-all hover:border-primary hover:shadow-lg",
  appointmentCardPast: "border-2 border-gray-200 rounded-xl overflow-hidden transition-all opacity-70",
  cardHeader: "flex justify-between items-center py-3 px-4 bg-gray-50 border-b border-gray-200",
  statusBadge: "text-white py-1 px-3 rounded-full text-[0.75rem] font-semibold uppercase",
  appointmentDate: "text-[0.85rem] text-gray-500 font-medium",
  cardBody: "p-4",
  examName: "m-0 mb-1 text-lg text-gray-800",
  specialty: "m-0 mb-4 text-[0.85rem] text-primary font-medium",
  patientInfo: "mb-3 p-3 bg-gray-50 rounded-md",
  patientName: "m-0 mb-1 font-semibold text-gray-800",
  patientEmail: "m-0 text-[0.85rem] text-gray-500",
  patientPhone: "m-0 text-[0.85rem] text-gray-500",
  timeInfo: "flex items-center gap-2 mb-3",
  time: "text-xl font-semibold text-gray-800",
  notes: "text-[0.85rem] text-gray-500 m-0 pt-3 border-t border-gray-200",
  cardActions: "flex gap-2 py-3 px-4 bg-gray-50 border-t border-gray-200 flex-wrap",
  btnConfirm: "flex-1 min-w-[80px] py-2 px-3 border-none rounded bg-green-600 text-white text-[0.8rem] font-medium cursor-pointer transition-all hover:bg-green-700",
  btnCancel: "flex-1 min-w-[80px] py-2 px-3 border-none rounded bg-amber-500 text-white text-[0.8rem] font-medium cursor-pointer transition-all hover:bg-amber-600",
  btnComplete: "flex-1 min-w-[80px] py-2 px-3 border-none rounded bg-blue-500 text-white text-[0.8rem] font-medium cursor-pointer transition-all hover:bg-blue-600",
  btnDelete: "flex-1 min-w-[80px] py-2 px-3 border-none rounded bg-red-500 text-white text-[0.8rem] font-medium cursor-pointer transition-all hover:bg-red-600",
  loading: "text-center p-8 text-gray-500",
} as const;
